---
- name: Apache installation for webservers
  hosts: amazon
  become: yes
  tasks:
   - name: install the latest version of Apache
     dnf:
       name: httpd
       state: latest

   - name: start Apache
     service:
      name: httpd
      state: started
      enabled: yes

- name: Apache installation for ubuntuservers
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install the latest version of Apache
      apt:
        name: apache2
        state: latest

    - name: Ensure Apache is enabled and started on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes