---
- name: Setup for Amazon Linux
  hosts: amazon
  become: yes
  tasks:
    - name: Install Apache and MySQL
      dnf:
        name:
          - httpd
          - mariadb105-server
          - wget
        state: latest

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

- name: Setup for Ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install Apache and MySQL
      apt:
        name:
          - apache2
          - mysql-server
          - wget
        state: latest

    - name: Ensure Apache is enabled and started on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes